#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Valeur par défaut
ALL_RUN=1
PARALLEL=0

# Traitement des options
while getopts "mp" opt; do
  case "$opt" in
    m)
      ALL_RUN=0
      ;;
    p)
      PARALLEL=1
      ;;
    *)
      echo "Usage: $0 [-m] [-p]"
      exit 1
      ;;
  esac
done

restore0Dir

# create mesh
runApplication blockMesh
runApplication checkMesh

# decompose mesh
if [ "$PARALLEL" -eq 1 ]; then
  runApplication decomposePar
fi

# Create foam.foam for paraview
touch foam.foam

# Run simulation
if [ "$ALL_RUN" -eq 1 ]; then

  if [ "$PARALLEL" -eq 1 ]; then
    runParallel $(getApplication)
    runApplication reconstructPar
  else
    runApplication $(getApplication)
  fi

fi


#------------------------------------------------------------------------------
